language: python
arch : 
  - amd64
  - ppc64le
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "pypy"
before_install:
  - | 
    if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then
     sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels
    fi
   jobs:
  exclude:
    - arch: ppc64le
      python: pypy
 
install:
  - pip install coveralls

script:
  - coverage run --source=babelfish setup.py test

after_success:
  - coveralls

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#babelfish"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
