language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then pip install coveralls; fi

script:
  # coverage fails on python 3.2
  - if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then coverage run --source=babelfish setup.py test; else python setup.py test; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then coveralls; fi

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#babelfish"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
