language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - pip install coveralls

script:
  - coverage run --source=babelfish setup.py test

after_success:
  - coveralls

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#babelfish"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
